eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 5
        metadataMap:
            instanceId: ${spring.application.name}:${random.value}
        preferIpAddress: true
server:
    port: 8082
spring:
    application:
        name: user-service
security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: user-srvr-psv
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: server
      user-authorization-uri: http://localhost:5000/oauth/authorize
    resource:
      user-info-uri:  http://localhost:5000/users/current
logging:
  level:
    root: debug