server:
  port: 8099
spring:
  application:
    name: turbine-metrics-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      instance-id: ${spring.application.name}:${random.value}
turbine:
  appConfig: ORDER-SERVICE, ORDER
  cluster-name-expression: new String("default")
  combine-host-port: true

